# Project information
site_name: Coding Interview Note
site_description: ğŸ“ Solutions and notes of the problems on online judge platforms like LeetCode, Codility and HackerRank.
site_author: Hsins
site_url: https://hsins.github.io/OJ-Note/

# Repository
repo_name: Hsins/OJ-Note
repo_url: https://github.com/Hsins/OJ-Note/
edit_uri: edit/docs/docs/

# Copyright
copyright: Copyright &copy; 2022 H.-H. Peng

# Configuration
theme:
  name: material
  custom_dir: overrides

  static_templates:
    - 404.html

  logo: assets/logo.png
  favicon: assets/logo.png

  language: zh-Hant
  features:
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - content.code.annotate
    - search.highlight
    - search.suggest

  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: grey
      accent: red
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: red
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  font:
    text: Roboto
    code: Roboto Mono

  icon:
    repo: fontawesome/brands/github-square
    admonition:
      note: octicons/tag-16
      abstract: octicons/checklist-16
      info: octicons/info-16
      tip: octicons/squirrel-16
      success: octicons/check-16
      question: octicons/question-16
      warning: octicons/alert-16
      failure: octicons/x-circle-16
      danger: octicons/zap-16
      bug: octicons/bug-16
      example: octicons/beaker-16
      quote: octicons/quote-16

  # Don't include Mkdocs JavaScript
  include_search_page: false
  search_index_only: true

# Extras
extra:
  alternate:
    - name: ç¹é«”ä¸­æ–‡
      link: ./
      lang: zh-Hant
    - name: English
      link: ./en/
      lang: en
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Hsins

# Contents
nav:
  - é¦–é : index.md
  - å°ˆæ¡ˆä»‹ç´¹:
      - é—œæ–¼æœ¬ç«™: intro/index.md
      - é¢¨æ ¼è¦ç¯„: intro/styleguide.md
      - åƒè€ƒè³‡æ–™: intro/references.md
  - æ¨¡æ¿æ•´ç†:
      - æ»‘å‹•çª—å£: patterns/sliding-window.md
      - é›™å‘æŒ‡é‡: patterns/two-pointers.md
      - å¿«æ…¢æŒ‡é‡: patterns/fast-slow-pointers.md
      - åˆä½µå€é–“: patterns/merge-intervals.md
      - å¾ªç’°æ’åº: patterns/cyclic-sort.md
      - In-place Reversal of Linked-List: patterns/in-place-reversal-of-linked-list.md
      - å»£åº¦å„ªå…ˆæœç´¢: patterns/breadth-first-search.md
      - æ·±åº¦å„ªå…ˆæœç´¢: patterns/depth-first-search.md
      - Two Heaps: patterns/two-heaps.md
      - Subsets: patterns/subsets.md
      - ä½å…ƒé‹ç®—: patterns/bitwise-xor.md
      - Top K Elements: patterns/top-k-elements.md
      - K-way Merge: patterns/k-way-merge.md
      - èƒŒåŒ…å•é¡Œ: patterns/0-or-1-knapsack.md
      - æ‹“å¢£æ’åº: patterns/topological-sort.md
  - LeetCode:
      - 0013. ç¾…é¦¬æ•¸å­—è½‰æ•´æ•¸: leetcode/roman-to-integer.md
      - 0021. åˆä½µå…©å€‹æœ‰åºéˆè¡¨: leetcode/merge-two-sorted-lists.md
      - 0025. K å€‹ä¸€çµ„ç¿»è½‰éˆè¡¨: leetcode/reverse-nodes-in-k-group.md
      - 0141. ç’°å½¢éˆè¡¨: leetcode/linked-list-cycle.md
      - 0142. ç’°å½¢éˆè¡¨ II: leetcode/linked-list-cycle-ii.md
      - 0143. é‡æ’éˆè¡¨: leetcode/reorder-list.md
      - 0160. ç›¸äº¤éˆè¡¨: leetcode/intersection-of-two-linked-lists.md
      - 0202. å¿«æ¨‚æ•¸: leetcode/happy-number.md
      - 0205. åŒæ§‹å­—ç¬¦ä¸²: leetcode/insomorphic-strings.md
      - 0206. åè½‰éˆè¡¨: leetcode/reverse-linked-list.md
      - 0217. å­˜åœ¨é‡è¤‡å…ƒç´ : leetcode/contains-duplicate.md
      - 0234. å›æ–‡éˆè¡¨: leetcode/palindrome-linked-list.md
      - 0242. æœ‰æ•ˆçš„å­—æ¯ç•°ä½è©: leetcode/valid-anagram.md
      - 0457. ç’°å½¢æ•¸çµ„æ˜¯å¦å­˜åœ¨å¾ªç’°: leetcode/circular-array-loop.md
      - 0876. éˆè¡¨çš„ä¸­é–“çµé»: leetcode/middle-of-the-linked-list.md

# Plugins
plugins:
  - tags
  - search:
      lang:
        - en
        - ja
  - minify:
      minify_html: true
  - i18n:
      default_language: zh
      languages:
        zh: ç¹é«”ä¸­æ–‡
        en: English
      nav_translations:
        en:
          # nav
          é¦–é : Home
          å°ˆæ¡ˆä»‹ç´¹: Intro
          æ¨¡æ¿æ•´ç†: Patterns
          # intro
          é—œæ–¼æœ¬ç«™: About
          é¢¨æ ¼è¦ç¯„: Style Guide
          åƒè€ƒè³‡æ–™: References
          # patterns
          æ»‘å‹•çª—å£: Sliding Window
          é›™å‘æŒ‡é‡: Two Pointers
          å¿«æ…¢æŒ‡é‡: Fast-slow Pointers
          åˆä½µå€é–“: Merge Intervals
          å¾ªç’°æ’åº: Cyclic Sort
          å»£åº¦å„ªå…ˆæœç´¢: Breadth First Search
          æ·±åº¦å„ªå…ˆæœç´¢: Depth First Search
          ä½å…ƒé‹ç®—: Bitwise XOR
          èƒŒåŒ…å•é¡Œ: 0/1 Knapsack
          æ‹“å¢£æ’åº: Topological Sort
          # LeetCode problems
          0013. ç¾…é¦¬æ•¸å­—è½‰æ•´æ•¸: 0013. Roman to Integer
          0021. åˆä½µå…©å€‹æœ‰åºéˆè¡¨: 0021. Merge Two Sorted Lists
          0025. K å€‹ä¸€çµ„ç¿»è½‰éˆè¡¨: 0025. Reverse Nodes in k-Group
          0141. ç’°å½¢éˆè¡¨: 0141. Linked List Cycle
          0142. ç’°å½¢éˆè¡¨: 0142. Linked List Cycle II
          0143. é‡æ’éˆè¡¨: 0143. Reorder List
          0160. ç›¸äº¤éˆè¡¨: 0160. Intersection of Two Linked Lists
          0202. å¿«æ¨‚æ•¸: 0202. Happy Number
          0205. åŒæ§‹å­—ç¬¦ä¸²: 0205. Insomorphic Strings
          0206. åè½‰éˆè¡¨: 0206. Reverse Linked List
          0234. å›æ–‡éˆè¡¨: 0234. Palindrome Linked List
          0217. å­˜åœ¨é‡è¤‡å…ƒç´ : 0217. Contains Duplicate
          0242. æœ‰æ•ˆçš„å­—æ¯ç•°ä½è©: 0242. Valid Anagram
          0457. ç’°å½¢æ•¸çµ„æ˜¯å¦å­˜åœ¨å¾ªç’°: 0457. Circular Array Loop
          0876. éˆè¡¨çš„ä¸­é–“çµé»: 0876. Middle of the Linked List

# Extensions
markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra_javascript:
  # MathJax
  - extra/js/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  # Tables
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - extra/js/tables.js

extra_css:
  - extra/css/home.css
  - extra/css/custom.css
